[package]
name = "sqlite-extension"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rusqlite = { git = "https://github.com/rusqlite/rusqlite.git", features = ["loadable_extension", "functions", "trace"]}
